### ISSUE TITLE
Different scenario causes cropping error

### ISSUE THREAD

**Issue by matthewma7** [OpenDataAnalytics/gaia#126]
The cropping for vector and raster data works for general cases.
But there is some scenario will cause errors. 

- Raster data
  - Crop region is bigger than the target
  - Crop region is entirely outside the target area
  - Some maybe special RGB datsaet will lose color in the cropped result
- Vector data
  - Crop region is entirely outside the target area

I uploaded [some example data](https://drive.google.com/drive/folders/1YTJ6gI1b8cIaBsqMpibhOvDui8PO6vgO?usp=sharing) here for these cases.

**Comment by johnkit** [comment]
@matthewma7 

* I cannot duplicate the "lose color" issue. Maybe we can look at that in the coming week.
* As for the other problems, I think that PR #127 fixes them. Do you want to review that before I merge?

**Comment by johnkit** [comment]
Resolve by PR #127
