### ISSUE TITLE
Specify a dependencies list

### ISSUE THREAD

**Issue by mgrauer** [OpenDataAnalytics/gaia#18]
The system dependencies are only specified in .travis.yml, which is probably fine for now.  Travis currently uses Ubuntu 12.04 images, and so the only dependency needed is `libgdal-dev`.

`matplotlib` installed via pip on Ubuntu 14.04 requires `libpng` and `freetype`, though `matplotlib` is only required for testing currently.

Maybe just tracking this here in the issue is good enough for now.

**Comment by mgrauer** [comment]
On Ubuntu 14.04 these are `libfreetype6-dev` and `libpng12-dev`.

**Comment by aashish24** [comment]
:+1: I think we need to sort it out. Currently geopandas requires some system packages as well.

**Comment by aashish24** [comment]
I had to install python flask as well.

**Comment by mgrauer** [comment]
@aashish24 what environment are you working in?  I didn't have to explicitly install flask at any point working on Ubuntu 14.04, with pip, without using a virtual env.

**Comment by aashish24** [comment]
I am ubuntu 14.04 as well.

**Comment by jbeezley** [comment]
I'm not sure why you need flask.  I have been running the tests and as far as I can tell, I don't have flask installed anywhere either.

**Comment by aashish24** [comment]
that happened when manually installed geopandas. If its not reproducible, then I wont worry about it.
