### ISSUE TITLE
Design and implement API for map algebra

### ISSUE THREAD

**Issue by aashish24** [OpenDataAnalytics/gaia#34]

**Comment by aashish24** [comment]
@essamjoubori @mbertrand ping

**Comment by mbertrand** [comment]
Examples: http://geoexamples.blogspot.com/2012/12/raster-calculations-with-gdal-and-numpy.html

**Comment by aashish24** [comment]
https://www.nrem.iastate.edu/files/w11-MapAlgebra_presentation5.pdf

**Comment by mbertrand** [comment]
I created [RasterMathProcess](https://github.com/OpenDataAnalytics/gaia/blob/3ba2ff099a8fd4abaaa77c933b579fb3a3e8bd08/gaia/processes.py#L279), using [gdal_calc method](https://github.com/OpenDataAnalytics/gaia/blob/3ba2ff099a8fd4abaaa77c933b579fb3a3e8bd08/gaia/gdal_functions.py#L206) which is a modification of GDAL's own [gdal_calc](http://www.gdal.org/gdal_calc.html) commandline tool.  The original commandline tool requires all input rasters to be the same size (rows x columns), but this code will warp all input rasters to the same size/bounds as the 1st input raster if necessary.

Several test cases for the process:
[Add 2 rasters (equation: A+ B)](https://github.com/OpenDataAnalytics/gaia/blob/3ba2ff099a8fd4abaaa77c933b579fb3a3e8bd08/tests/cases/test_processors.py#L170)
[Multiply a raster by 2 (equation: A * 2)](https://github.com/OpenDataAnalytics/gaia/blob/3ba2ff099a8fd4abaaa77c933b579fb3a3e8bd08/tests/cases/test_processors.py#L209)

**Comment by aashish24** [comment]
this is great @mbertrand I will have a look. In the mean time, can you move RasterMathProcess into its own file (unless you have a strong feeling otherwise)?

**Comment by mbertrand** [comment]
@aashish24 I can do that.  Do you want every process to have its own file (we'll end up with a lot of them)?  Or maybe one file for vector data processes, and one file for raster-based processes?  Currently there are 2 raster processes (RasterMath and Subset) and I'd like to add at least one more (RasterZonalStatistics).

**Comment by aashish24** [comment]
thanks @mbertrand I was thinking one file per data type (vector and raster) as you suggested.

**Comment by mbertrand** [comment]
Moved raster processes to [processes_raster.py](https://github.com/OpenDataAnalytics/gaia/commit/397e933a1b4da4c84acccad52f23307da5a806e3#diff-f8e546334fa73a780a93af6bab5f5d9e)

Vector processes are now in [processes_vector.py]( https://github.com/OpenDataAnalytics/gaia/commit/397e933a1b4da4c84acccad52f23307da5a806e3#diff-f075014100af8e4a05659eed43d62063)

Adjusted GaiaRequestParser to find the correct Processor class by [creating a dict of processor classes from both files](https://github.com/OpenDataAnalytics/gaia/commit/397e933a1b4da4c84acccad52f23307da5a806e3#diff-4a07024d607de815a3e83e29a14ee45eR13)

**Comment by mbertrand** [comment]
@aashish24 Here is a new unit test for RasterMath using logical operators (logical_or, logical_and): [test_rastermath_logical_operators](https://github.com/OpenDataAnalytics/gaia/blob/ca59279da20d0eda45fdcc513d29d45dc9cc142b/tests/cases/test_processors.py#L289)

**Comment by aashish24** [comment]
thanks @mbertrand
