### ISSUE TITLE
Added Travis CI build / test support

### ISSUE THREAD

**Issue by aashish24** [OpenDataAnalytics/gaia#38]

**Comment by mbertrand** [comment]
@aashish24 , travis has been implemented for Python 2.7.  Is Python 3 support also required?

https://travis-ci.org/OpenDataAnalytics/gaia
https://github.com/OpenDataAnalytics/gaia/blob/gaia_api/.travis.yml

**Comment by aashish24** [comment]
> Is Python 3 support also required

No, not for now but it would be nice if we can add a issue for it.

**Comment by aashish24** [comment]
Is this travis upto-date with current code?

**Comment by mbertrand** [comment]
It is up-to-date on master and gaia_api branches.

**Comment by aashish24** [comment]
@mbertrand thanks, I will push a dummy branch and if I see travis results showing up on github interface, I will close this issue.
