### ISSUE TITLE
Add support for Jenkins dashboard

### ISSUE THREAD

**Issue by aashish24** [OpenDataAnalytics/gaia#39]

**Comment by mbertrand** [comment]
Is there a particular jenkins instance you want this on?  Epidemico has a jenkins instance but it is not publicly accessible.

**Comment by aashish24** [comment]
Hey @mbertrand we need a public instance. We can host it at Kitware but we decided to use jenkins since you are familiar with it. Buildbot would be another option.

**Comment by mbertrand** [comment]
Our devops man Lou will look into using our jenkins server and having build/test results displayed on github as explained [here](http://stackoverflow.com/questions/14274293/show-current-state-of-jenkins-build-on-github-repo).

**Comment by aashish24** [comment]
- [ ] Have Jenkins public instance hosted at Kitware / Epidemico
- [ ] Have Jenkins results displayed on Github
- [ ] Deployment script that can setup Jenkins for Gaia

**Comment by aashish24** [comment]
> Our devops man Lou will look into using our jenkins server and having build/test results displayed on github as explained here.

Sounds good @mbertrand I updated the task above. Please let me know if it looks good to you. Thanks,

**Comment by mbertrand** [comment]
@aashish24 this is not going to work out from our jenkins server.  It's been setup but currently doesn't show any more testing results than travis does from the output console.  Build results cannot be seen without having a jenkins account and opening it up to anonymous public viewing is not an option.

**Comment by mbertrand** [comment]
![screen shot 2016-03-04 at 9 52 26 am](https://cloud.githubusercontent.com/assets/187676/13530348/eaece08a-e1ee-11e5-8396-88b4d15f7c58.png)

**Comment by aashish24** [comment]
thanks @mbertrand let's not worry about Jenkins for now.
