### ISSUE TITLE
Save current master as master-old

### ISSUE THREAD

**Issue by aashish24** [OpenDataAnalytics/gaia#40]

**Comment by mbertrand** [comment]
https://github.com/OpenDataAnalytics/gaia/tree/master_old

**Comment by jbeezley** [comment]
We may consider making these branch names more specific.  There is already https://github.com/OpenDataAnalytics/gaia/tree/old-master containing the prior iteration.

**Comment by mbertrand** [comment]
How about master_20151118  and master_20140926 based on their last commit dates?

**Comment by jbeezley** [comment]
That works for me.

**Comment by aashish24** [comment]
> How about master_20151118 and master_20140926 based on their last commit dates?

+1

**Comment by mbertrand** [comment]
OK, done.

**Comment by aashish24** [comment]
Thanks @mbertrand  assuming that its master_2015**** I can closing it

**Comment by aashish24** [comment]
sorry I am closing it.
