### ISSUE TITLE
Add geocoding to Gaia

### ISSUE THREAD

**Issue by mbertrand** [OpenDataAnalytics/gaia#48]
@aashish24 please edit/comment as necessary.

Use [geopy](https://github.com/geopy/geopy) to add geocoding capability to Gaia
- new GeocodeProcess class
- use the geocoder specified in process argument (options include OpenStreetMap Nominatim, ESRI ArcGIS, Google Geocoding API (V3), Baidu Maps, Bing Maps API, Yahoo! PlaceFinder, Yandex, IGN France, GeoNames, NaviData, OpenMapQuest, What3Words, OpenCage, SmartyStreets, geocoder.us, and GeocodeFarm)
- default geocoder if none specified will be: Google?
- Allow reverse geocoding option (given coordinates, find nearest placename)
- Output.data should be a geopandas dataframe

**Comment by aashish24** [comment]
@mbertrand there are two parts to it. Geocoding and reverse geocoding and geocoding for tweets. Geocoding for tweets is a high priority. I will send a document to essam and you in an email. 

Also, @jbeezley has developed some code in the past that can ingest geonames database and have our own geocoding services.

**Comment by mgrauer** [comment]
We did this to some degree in [Minerva](https://github.com/Kitware/minerva/blob/a1b7440e0109430e96c86bb76a087f1d75191a16/server/rest/dataset.py#L190-L214) a while back, but haven't used it lately.  FYI, in case it useful.

**Comment by aashish24** [comment]
we implemented it outside gaia
