### ISSUE TITLE
Relocate gdal_functions processes_vector and other geo classes

### ISSUE THREAD

**Issue by aashish24** [OpenDataAnalytics/gaia#52]
I suggest we relocate them under gaia/geo @mbertrand @kotfic thoughts?

**Comment by aashish24** [comment]
@mbertrand this is a low priority, let's discuss it in the next sprint planning meeting.

**Comment by mbertrand** [comment]
Under gaia/geo is fine with me.

**Comment by aashish24** [comment]
Sounds good. Who shoudl we assign?
