### ISSUE TITLE
Plugin framework for Gaia

### ISSUE THREAD

**Issue by mbertrand** [OpenDataAnalytics/gaia#69]
Goal: Allow 3rd-party developers to add plugins to Gaia

Basic design:

- add an empty plugins module to gaia, where additional plugin submodules can be placed.
- each module can optionally include a requirements.txt file and config file.  
    - Manually install the requirements if necessary (pip install requirements.txt)
- Gaia's [current config parser](https://github.com/OpenDataAnalytics/gaia/blob/master/gaia/core.py) will recursively search through the plugins folder to add any  configuration settings.
- Examples to include a gaia plugin in a script:
    - import gaia.plugins.my_plugin
    - from gaia.plugins.my_plugin import MyGaiaPluginIO, MyPluginProcessor

@aashish24 @dorukozturk please review.

**Comment by jbeezley** [comment]
I would avoid this kind of a plugin structure.  This is how girder's plugins work, and it causes a number of problems with deploying and maintenance.  A better approach is to use setuptools' "entry_points".  Pylons provides a basic example of how it works [here](http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/entry_points_and_plugins.html).  Doing it this way eliminates the need for manual management of dependencies and makes deployment easier (just pip install).

**Comment by kotfic** [comment]
I agree with @jbeezley, directory based plugins quickly run into scaleability issues.  A very compact example of how to use entry-points exists in this PR https://github.com/girder/girder_worker/pull/29 As you can see [here](https://github.com/girder/girder_worker/blob/d9d676e3c530bc16ca9c1de4d5b61d9e842b3fc5/girder_worker/__main__.py#L5-L10)  we dynamically add celery tasks from other packages by creating a custom 'girder_worker.tasks' entry point. Any installed module that defines this entry_point can add tasks to the celery worker.

**Comment by mbertrand** [comment]
Thanks @jbeezley and @kotfic I will use the entry_points approach.

**Comment by aashish24** [comment]
I agree with both @jbeezley @kotfic

**Comment by mbertrand** [comment]
@jbeezley  and @kotfic when you have a chance could you take a look at:

[gaia_plugin_demo](https://github.com/mbertrand/gaia_plugin_demo)
[gaia.parser.load_plugins](https://github.com/OpenDataAnalytics/gaia/blob/plugins/gaia/parser.py#L44-L53)

and let me know if that's generally what you had in mind.

gaia_plugin_demo contains new IO and Processor classes in several modules, with this in its setup.py file:

```python
  entry_points={
    'gaia.plugins': [
            "fake_plugin = my_gaia_plugins.fake_plugin",
            "another_fake_plugin = my_gaia_plugins.another_fake_plugin"
        ]
}
```

In the gaia plugins branch, there is a load_plugins method which is in turn called in the deserialize method:

```python
# Import plugin classes
def load_plugins():
    plugin_modules = []
    for ep in pr.iter_entry_points(group='gaia.plugins'):
        module = ep.load()
        plugin_modules.append(importlib.import_module(module.__name__))
        logger.debug("Loaded plugin {}: {}".format(ep.name, module))

    for plugin in plugin_modules:
        valid_classes.extend([x[0] for x in inspect.getmembers(
plugin, inspect.isclass)])
```

So when sending a json file like this to Gaia's parser:

```javascript
{
  "_type": "my_gaia_plugins.fake_plugin.FakeProcess",
  "inputs": [
    {
      "name": "input",
      "_type": "my_gaia_plugins.fake_plugin.FakeIO",
      "uri": "/tmp/bogus.geojson"
    },
    {
      "name": "input",
      "_type": "my_gaia_plugins.another_fake_plugin.AnotherFakeIO",
      "uri": "/tmp/bogus.tif"
    }
  ],
  "var_col": "num_hospitals"
}
```

The output is:
```
Created FakeIO
Created AnotherFakeIO
Created FakeProcess
Compute something with FakeProcess
Process complete.
```

**Comment by jbeezley** [comment]
Yup, that looks about right.  You'll eventually want to publish these plugins on pypi, so it would be good to establish a naming convention so they are easy to find (something like `gaia-*`).

**Comment by aashish24** [comment]
@mbertrand should we close this?
