### ISSUE TITLE
Geotrellis integration with Gaia

### ISSUE THREAD

**Issue by mbertrand** [OpenDataAnalytics/gaia#74]
@dorukozturk's [geotrellis-pipeline](https://github.com/OpenGeoscience/nex/tree/master/geotrellis-pipeline) looks like a good example of how to approach this: creating JAR's for Geotrellis apps/functions and calling them via subprocess in python.
- For the Landsat example, maybe we could modify it so that the [MaskNearRedAndInfrared](https://github.com/geotrellis/geotrellis-landsat-tutorial/blob/master/src/main/scala/tutorial/MaskRedAndNearInfrared.scala) and [CreateNDVI](https://github.com/geotrellis/geotrellis-landsat-tutorial/blob/master/src/main/scala/tutorial/CreateNDVIPng.scala) methods are available outside of a webserver, and operate on/output an entire geotiff rather than tiles?  If that approach makes sense, then use it to implement other processes like generic raster math, subsetting, etc.
- Spark integration: should Spark always be used with Geotrellis functions?  Or used only for certain processes and/or only if an optional parameter is supplied?

**Comment by mbertrand** [comment]
@dorukozturk I played around with your code a bit: https://github.com/OpenGeoscience/nex/compare/master...mbertrand:landsat?expand=1

**Comment by mbertrand** [comment]
Based on discussion with @dorukozturk: Spark integration should probably always be used with geotrellis, since the library's major advantage over GDAL is being able to use Spark to handle very large datasets. GDAL is better & easier for smaller datasets.

**Comment by mbertrand** [comment]
Initial gaia plugin for geotrellis is here: https://github.com/OpenDataAnalytics/gaia-geotrellis-plugin

Just a couple of processes (cloudmask, ndvi) based on the original examples.

TODO: Spark integration, geotrellis implementation of map algebra process.

**Comment by aashish24** [comment]
@mbertrand should we close this issue?
