### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by snowman2** [OpenDataAnalytics/gaia#79]
Hello,

I am interested in making this available via Anaconda's conda-forge channel (see: https://github.com/conda-forge/staged-recipes). Anaconda makes it simpler for testing and deploying your code in multiple operating systems. Is this something you would be interested in?

**Comment by mbertrand** [comment]
@snowman2 That sounds great to me, what do you think @aashish24?

**Comment by aashish24** [comment]
@snowman2 @mbertrand absolutely! Sorry for some reason I didn't see this in my email.

**Comment by aashish24** [comment]
@snowman2 @mbertrand I think we can close this issue now?
