### ISSUE TITLE
Add description of the project to the README file.

### ISSUE THREAD

**Issue by jcfr** [OpenDataAnalytics/gaia#8]
For example:
```
Gaia provides data processing, transformation, and analysis capabilities specifically targeted for spatial datasets. It is built on top of popular open source packages such as GDAL,  PROJ4, NUMPY, OpenClimateGIS, Shapely and Fiona. It can fetch data from multiple sources such as tile servers and databases. 
```

**Comment by aashish24** [comment]
Nice text @jcfr

**Comment by mbertrand** [comment]
I'll replace the current description on the [gaia_api branch](https://github.com/OpenDataAnalytics/gaia/blob/gaia_api/README.md) with jcfr's.

**Comment by mbertrand** [comment]
The current description is now:

"Gaia is a geospatial utilities plugin for Girder, jointly developed by Kitware and Epidemico. It provides data processing, transformation, and analysis capabilities specifically targeted for spatial datasets. Gaia is built on top of popular open source packages such as GDAL and GeoPandas. It will fetch data from multiple sources such as files and databases."
